---
#########################
#########################
## Golang Linter rules ##
#########################
#########################

# configure golangci-lint
# see https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
issues:
  exclude-rules:
    - path: _test\.go
      linters:
      - dupl
      - gosec
      - goconst
linters:
  enable:
    - golint
    - gosec
    - unconvert
    - gocyclo
    - goconst
    - goimports
    - maligned
    - gocritic
linters-settings:
  errcheck:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: false
  govet:
    # report about shadowed variables
    check-shadowing: false
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 30
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true

# output configuration options
output:
  format: github-actions

