name: Test Build Container

on:
  pull_request:
    branches-ignore: []

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.repo }}

      - name: Build Test
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: test:${{ github.sha }}
